"""Runtime primitives for knowbase."""

from __future__ import annotations

from importlib import import_module

_EXPORTS = {
    "RuntimeRunRequest": "runtime.contracts",
    "RuntimeAction": "runtime.contracts",
    "RuntimeDecision": "runtime.contracts",
    "RuntimeObservation": "runtime.contracts",
    "RuntimeMemorySnapshot": "runtime.contracts",
    "RuntimeTurnInput": "runtime.contracts",
    "RuntimeRunResult": "runtime.contracts",
    "RuntimeRunState": "runtime.core.state",
    "KnowbaseRuntimeService": "runtime.service",
    "RuntimeCapabilityExecutor": "runtime.actions.capability_executor",
    "RuntimeActionRunner": "runtime.actions.action_runner",
    "RuntimeAgentPort": "runtime.loop.agent",
    "RuntimeLoopAgent": "runtime.loop.agent",
    "RuntimeTurnPlannerPort": "runtime.loop.turn_planner",
    "UnconfiguredRuntimeTurnPlanner": "runtime.loop.turn_planner",
    "RuntimeTurnPlanner": "runtime.loop.turn_planner",
    "RuntimeDecisionPrompt": "runtime.llm.prompt_builder",
    "RuntimePromptBuilderPort": "runtime.llm.prompt_builder",
    "DefaultRuntimePromptBuilder": "runtime.llm.prompt_builder",
    "RuntimeModelRequest": "runtime.providers.openai_runtime_adapter",
    "RuntimeModelResponse": "runtime.providers.openai_runtime_adapter",
    "RuntimeModelAdapterPort": "runtime.providers.openai_runtime_adapter",
    "OpenAIRuntimeModelAdapter": "runtime.providers.openai_runtime_adapter",
    "DefaultRuntimeModelAdapter": "runtime.providers.openai_runtime_adapter",
    "OpenAIChatRequest": "runtime.providers.openai_client",
    "OpenAIChatResponse": "runtime.providers.openai_client",
    "OpenAIClientPort": "runtime.providers.openai_client",
    "DefaultOpenAIClient": "runtime.providers.openai_client",
    "RuntimeDecisionActionPayload": "runtime.llm.decision_parser",
    "RuntimeDecisionPayload": "runtime.llm.decision_parser",
    "RUNTIME_DECISION_PAYLOAD_JSON_SCHEMA": "runtime.llm.decision_parser",
    "build_runtime_decision_payload_schema": "runtime.llm.decision_parser",
    "RuntimeDecisionParserPort": "runtime.llm.decision_parser",
    "DefaultRuntimeDecisionParser": "runtime.llm.decision_parser",
    "RuntimeDecisionConstraints": "runtime.llm.decisioning",
    "RuntimeProposedActionKind": "runtime.llm.decisioning",
    "RuntimeProposedAction": "runtime.llm.decisioning",
    "RuntimeDecisionDraft": "runtime.llm.decisioning",
    "RuntimeDecisionGeneratorPort": "runtime.llm.decisioning",
    "DefaultRuntimeDecisionGenerator": "runtime.llm.decisioning",
    "RuntimeDecisionNormalizer": "runtime.llm.decisioning",
    "RuntimePlannerContext": "runtime.loop.planner_components",
    "RuntimePlannerObservation": "runtime.loop.planner_components",
    "RuntimePlannerStopAssessment": "runtime.loop.planner_components",
    "RuntimeObservationAssemblerPort": "runtime.loop.planner_components",
    "RuntimeStopEvaluatorPort": "runtime.loop.planner_components",
    "RuntimeLoopEngine": "runtime.loop.engine",
    "RuntimeMemoryManager": "runtime.core.memory",
    "RuntimePolicy": "runtime.core.policy",
    "RuntimeTerminationDecision": "runtime.core.termination",
    "RuntimeTerminationPolicy": "runtime.core.termination",
}


def __getattr__(name: str):
    module_name = _EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(module_name)
    value = getattr(module, name)
    globals()[name] = value
    return value


__all__ = [
    "RuntimeRunRequest",
    "RuntimeAction",
    "RuntimeDecision",
    "RuntimeObservation",
    "RuntimeMemorySnapshot",
    "RuntimeTurnInput",
    "RuntimeRunResult",
    "RuntimeRunState",
    "KnowbaseRuntimeService",
    "RuntimeCapabilityExecutor",
    "RuntimeAgentPort",
    "RuntimeLoopAgent",
    "RuntimeTurnPlannerPort",
    "UnconfiguredRuntimeTurnPlanner",
    "RuntimeTurnPlanner",
    "RuntimeDecisionPrompt",
    "RuntimePromptBuilderPort",
    "DefaultRuntimePromptBuilder",
    "RuntimeModelRequest",
    "RuntimeModelResponse",
    "RuntimeModelAdapterPort",
    "OpenAIRuntimeModelAdapter",
    "DefaultRuntimeModelAdapter",
    "OpenAIChatRequest",
    "OpenAIChatResponse",
    "OpenAIClientPort",
    "DefaultOpenAIClient",
    "RuntimeDecisionActionPayload",
    "RuntimeDecisionPayload",
    "RUNTIME_DECISION_PAYLOAD_JSON_SCHEMA",
    "build_runtime_decision_payload_schema",
    "RuntimeDecisionParserPort",
    "DefaultRuntimeDecisionParser",
    "RuntimeDecisionConstraints",
    "RuntimeProposedActionKind",
    "RuntimeProposedAction",
    "RuntimeDecisionDraft",
    "RuntimeDecisionGeneratorPort",
    "DefaultRuntimeDecisionGenerator",
    "RuntimeDecisionNormalizer",
    "RuntimePlannerContext",
    "RuntimePlannerObservation",
    "RuntimePlannerStopAssessment",
    "RuntimeObservationAssemblerPort",
    "RuntimeStopEvaluatorPort",
    "RuntimeActionRunner",
    "RuntimeLoopEngine",
    "RuntimeMemoryManager",
    "RuntimePolicy",
    "RuntimeTerminationDecision",
    "RuntimeTerminationPolicy",
]
