"""Runtime primitives for knowbase."""

from __future__ import annotations

from importlib import import_module

_EXPORTS = {
    "RuntimeRunRequest": "runtime.contracts",
    "RuntimeAction": "runtime.contracts",
    "RuntimeDecision": "runtime.contracts",
    "RuntimeObservation": "runtime.contracts",
    "RuntimeMemorySnapshot": "runtime.contracts",
    "RuntimeTurnInput": "runtime.contracts",
    "RuntimeRunResult": "runtime.contracts",
    "RuntimeRunState": "runtime.memory.state",
    "KnowbaseRuntimeService": "runtime.service",
    "RuntimeCapabilityExecutor": "runtime.execution.capability_executor",
    "RuntimeActionRunner": "runtime.execution.action_runner",
    "RuntimeTurnPlannerPort": "runtime.loop.turn_planner",
    "UnconfiguredRuntimeTurnPlanner": "runtime.loop.turn_planner",
    "RuntimeTurnPlanner": "runtime.loop.turn_planner",
    "RuntimeDecisionPrompt": "runtime.llm.prompt_builder",
    "RuntimePromptBuilderPort": "runtime.llm.prompt_builder",
    "DefaultRuntimePromptBuilder": "runtime.llm.prompt_builder",
    "RuntimeDecisionActionPayload": "runtime.llm.decision_parser",
    "RuntimeDecisionPayload": "runtime.llm.decision_parser",
    "RUNTIME_DECISION_PAYLOAD_JSON_SCHEMA": "runtime.llm.decision_parser",
    "build_runtime_decision_payload_schema": "runtime.llm.decision_parser",
    "RuntimeDecisionParserPort": "runtime.llm.decision_parser",
    "DefaultRuntimeDecisionParser": "runtime.llm.decision_parser",
    "RuntimeDecisionConstraints": "runtime.llm.decisioning",
    "RuntimeProposedAction": "runtime.llm.decisioning",
    "RuntimeDecisionDraft": "runtime.llm.decisioning",
    "RuntimeDecisionGeneratorPort": "runtime.llm.decisioning",
    "DefaultRuntimeDecisionGenerator": "runtime.llm.decisioning",
    "RuntimeDecisionNormalizer": "runtime.llm.decisioning",
    "RuntimePlannerContext": "runtime.loop.planner_components",
    "RuntimePlannerObservation": "runtime.loop.planner_components",
    "RuntimePlannerStopAssessment": "runtime.loop.planner_components",
    "RuntimeObservationAssemblerPort": "runtime.loop.planner_components",
    "RuntimeStopEvaluatorPort": "runtime.loop.planner_components",
    "RuntimeLoopEngine": "runtime.loop.engine",
    "CompletionDecision": "runtime.completion.decision",
    "RuntimeCompletionGate": "runtime.completion.gate",
    "RuntimeChildRunAdapter": "runtime.subrun.child_adapter",
    "RuntimeChildRunExecutorPort": "runtime.subrun.child_adapter",
    "RuntimeOrchestrator": "runtime.orchestration.runner",
    "RuntimeOrchestrationResult": "runtime.orchestration.runner",
    "RuntimeSubRunLauncher": "runtime.subrun.contracts",
    "RuntimeSubRunRequest": "runtime.subrun.contracts",
    "RuntimeSubRunResult": "runtime.subrun.contracts",
    "VerificationSubRunResultMapper": "runtime.subrun.result_mapper",
    "RuntimeMemoryManager": "runtime.memory.manager",
    "RuntimePolicy": "runtime.execution.policy",
    "RuntimeTerminationDecision": "runtime.loop.termination",
    "RuntimeTerminationPolicy": "runtime.loop.termination",
    "RuntimeTraceRecorder": "runtime.trace.recorder",
    "VerificationResult": "runtime.verification.contracts",
    "RuntimeDeterministicVerifier": "runtime.verification.deterministic",
    "RuntimeVerificationContext": "runtime.verification.executor",
    "RuntimeVerificationExecutor": "runtime.verification.executor",
    "RuntimeVerificationExecutorPort": "runtime.verification.executor",
    "RuntimeVerificationProfile": "runtime.verification.profile",
    "RuntimeAcceptanceSpec": "runtime.contracts",
    "RuntimeRepairPolicy": "runtime.contracts",
    "RuntimeStopPolicy": "runtime.contracts",
    "RuntimeRiskPolicy": "runtime.contracts",
    "RuntimeWorkProfile": "runtime.contracts",
}


def __getattr__(name: str):
    module_name = _EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(module_name)
    value = getattr(module, name)
    globals()[name] = value
    return value


__all__ = [
    "RuntimeRunRequest",
    "RuntimeAction",
    "RuntimeDecision",
    "RuntimeObservation",
    "RuntimeMemorySnapshot",
    "RuntimeTurnInput",
    "RuntimeRunResult",
    "RuntimeRunState",
    "KnowbaseRuntimeService",
    "RuntimeCapabilityExecutor",
    "RuntimeTurnPlannerPort",
    "UnconfiguredRuntimeTurnPlanner",
    "RuntimeTurnPlanner",
    "RuntimeDecisionPrompt",
    "RuntimePromptBuilderPort",
    "DefaultRuntimePromptBuilder",
    "RuntimeDecisionActionPayload",
    "RuntimeDecisionPayload",
    "RUNTIME_DECISION_PAYLOAD_JSON_SCHEMA",
    "build_runtime_decision_payload_schema",
    "RuntimeDecisionParserPort",
    "DefaultRuntimeDecisionParser",
    "RuntimeDecisionConstraints",
    "RuntimeProposedAction",
    "RuntimeDecisionDraft",
    "RuntimeDecisionGeneratorPort",
    "DefaultRuntimeDecisionGenerator",
    "RuntimeDecisionNormalizer",
    "RuntimePlannerContext",
    "RuntimePlannerObservation",
    "RuntimePlannerStopAssessment",
    "RuntimeObservationAssemblerPort",
    "RuntimeStopEvaluatorPort",
    "RuntimeActionRunner",
    "RuntimeLoopEngine",
    "CompletionDecision",
    "RuntimeChildRunAdapter",
    "RuntimeChildRunExecutorPort",
    "RuntimeOrchestrator",
    "RuntimeOrchestrationResult",
    "RuntimeSubRunLauncher",
    "RuntimeSubRunRequest",
    "RuntimeSubRunResult",
    "VerificationSubRunResultMapper",
    "RuntimeMemoryManager",
    "RuntimePolicy",
    "RuntimeTerminationDecision",
    "RuntimeTerminationPolicy",
    "RuntimeCompletionGate",
    "RuntimeTraceRecorder",
    "VerificationResult",
    "RuntimeDeterministicVerifier",
    "RuntimeVerificationContext",
    "RuntimeVerificationExecutor",
    "RuntimeVerificationExecutorPort",
    "RuntimeVerificationProfile",
    "RuntimeAcceptanceSpec",
    "RuntimeRepairPolicy",
    "RuntimeStopPolicy",
    "RuntimeRiskPolicy",
    "RuntimeWorkProfile",
]
